### ISSUE TITLE
Spring quickstart guide link is broken 

### ISSUE THREAD

**Issue by alamages** [pivotal-cf/docs-redis#124]
https://github.com/pivotal-cf/docs-redis/blob/9d366a471ac0b43cb6d310e7ccbcd222988d84b3/quickstart.html.md.erb#L245

**Comment by jncd** [comment]
Hi @zvance 
Can you find a fresh link to this quickstart guide? 
It looks like the directory, https://docs.spring.io/spring-session/docs/current/reference/html5/guides/ was modified Jan 25, 2018. It could be that the quickstart was removed then. 
I'll comment out the dud link for now.
tia, Jane

**Comment by zvance** [comment]
https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html

**Comment by jncd** [comment]
Thanks @zvance 
Adding this link today.
