### ISSUE TITLE
Markdown can be seen in link

### ISSUE THREAD

**Issue by aclevername** [pivotal-cf/docs-redis#210]
You can see markdown in the note at the top of this section:
http://docs.pivotal.io/redis/1-13/installing.html#dedicated-vm-config

"See these instructions to \[disable Shared-VM and Dedicated-VM Plans](#disable-shared-dedicated)"

paired with @snneji

**Comment by jncd** [comment]
Hi @aclevername (Jake)
Thanks for reporting this bug. It's fixed now. (If you don't see it, try doing a hard refresh on your browser.)
jane
