### ISSUE TITLE
docs-redis/monitoring.html.md.erb Line: 455 Description is same as Memory Fragmentation Ratio

### ISSUE THREAD

**Issue by ichandan16** [pivotal-cf/docs-redis#326]
Hi , 
In `docs-redis/monitoring.html.md.erb` Line: **455** Description for `**Keyspace Hits / Keyspace Misses + Keyspace Hits**` is same as `**Memory Fragmentation Ratio**`.

https://docs.pivotal.io/redis/1-14/monitoring.html#Redis-KPIs

Thanks,
Chandan

**Comment by snneji** [comment]
Hi @ichandan16, I have passed this issue on to the Redis team and we'll update the docs to fix it. Thanks for letting us know. :)

**Comment by MirahImage** [comment]
Hi @ichandan16, thanks for bringing this to our attention.
