### ISSUE TITLE
Missing connectivity to BOSH Director on TCP 8844

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/docs-redis#379]
Needed for BOSH CredHub. This is missing from the documentation. Actually it is needed for more than one tile.

**Comment by snneji** [comment]
Hi @ywei2017, I apologize for taking so long to get back to you. We have updated the networking tables in Redis here: https://docs.pivotal.io/redis/2-2/odnetworking.html#network-rules, and in RabbitMQ here: https://docs.pivotal.io/rabbitmq-cf/1-17/about.html#network-rules.

We will work with other services to ensure their port list is up to date.

Thank you for bringing this to our attention.
