### ISSUE TITLE
Use non-secure communication for metrics

### ISSUE THREAD

**Issue by FaKeller** [pivotal-cf/docs-redis#55]
While trying to install PCF Redis on ER v1.10 I run into the same issue as described in the [documentation of RabbitMQ](https://docs.pivotal.io/rabbitmq-cf/1-7/metrics_logging.html#metrics). 

```
Cannot generate manifest for product Redis: Error in (( .properties.metrics_tls_disabled.value 
? ..cf.etcd_server.ips : .properties.etcd_machines.parsed_strings )): unknown job 
"etcd_server" (Product "Redis" / Job: nil)
```

I have noticed the hint next to the checkbox in the OpsManager saying "Uncheck this on PCF1.10 or later" but finding that in the [installation documentation](https://docs.pivotal.io/redis/1-7/installing.html) in the first place (or at least a hint to the [separate metrics section](https://docs.pivotal.io/redis/1-7/monitoring.html) where the version specifics are also explained) would really be helpful!

**Comment by pspinrad** [comment]
Thanks @FaKeller -- reworded and changed image on the two pages you point to, to show box unchecked, as it needs to be for PCF v1.10:
http://docs-pcf-staging.cfapps.io/redis/1-7/installing.html#securecomms
http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-7/metrics_logging.html#metrics

Should be clearer now, let us know!

**Comment by FaKeller** [comment]
Thanks, looks good! :-)
