### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-redis#94]
Search for "broke metrics" - should be "broker metrics"

**Comment by ghanna2017** [comment]
Thanks @agregory999 ...I can't find this typo. Please let me know which file you found it in and which version of the redis docs. Thanks, Gigi

**Comment by jncd** [comment]
@agregory999 and @ghanna2017 I found this typo in v1.8 and v1.9.
Thanks. Should appear fixed in production soon!
